language: objective-c
script:
  - xctool -project travis_practice.xcodeproj -scheme travis_practice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project travis_practice.xcodeproj -scheme travis_practice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
